#import "@preview/charged-ieee:0.1.4": ieee
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge
#import "@preview/ctheorems:1.1.3": *

// This fix prevents the "expected string or function" error in charged-ieee
#show figure.where(kind: "theorem"): set figure(numbering: "1.1")

#let theorem = thmbox(
  "theorem",
  "Theorem",
  inset: 0em,
)

#let lemma = thmbox(
  "theorem",
  "Lemma",
  inset: 0em,
)

#let remark = thmbox(
  "theorem",
  "Remark",
  inset: 0em,
)

#let corollary = thmplain(
  "corollary",
  "Corollary",
  base: "theorem",
  inset: 0em,
)

#let definition = thmbox(
  "definition",
  "Definition",
  inset: 0em,
)

#let example = thmplain("example", "Example").with(numbering: none)
#let proof = thmproof("proof", "Proof")

#show: ieee.with(
  title: [Principal Type Inference for the Simply Typed Lambda Calculus: A Lean Formalisation],
  authors: (
    (
      name: "xiaoshihou514",
      email: "xiaoshihou@tutamail.com",
    ),
  ),
  abstract: [
    This paper presents a formalization in the Lean theorem prover of a principal-type inference algorithm for the simply typed lambda calculus. The formalization demonstrates how dependent types and inductive families in Lean can be used to encode invariants that simplify reasoning about substitution and variable occurrence.
  ],
  index-terms: (
    "type inference",
    "dependent types",
    "simply typed lambda calculus",
    "formalisation",
  ),
  bibliography: bibliography("refs.bib"),
)
#show: thmrules

= Introduction

The simply typed lambda calculus (STLC), introduced by Church @church1940 and studied algebraically by Curry @curry1934, is the theoretical foundation of typed functional programming. A central algorithmic question is _principal type inference_: given a term $t$, compute a most-general typing judgement $Gamma tack.r t : tau$ such that every other typing judgement is an instance of it. Hindley @hindley1969 showed that principal types always exist for the STLC; Milner @milner1978 and Damas and Milner @damas1982 later extended the result to polymorphic $lambda$-calculi.

Robinson's unification algorithm @robinson1965 is the computational engine underlying most type-inference procedures. Despite its importance, machine-checked proofs of its correctness remain relatively rare in the literature, partly because termination is non-obvious: the standard argument requires a well-founded measure on the number of distinct type variables together with a cardinality squeeze lemma.

This report describes a complete Lean 4 @lean4 formalisation of:

+ The STLC grammar (types, terms) and a type-assignment checker.
+ Principal algorithm for STLC implemented in Lean 4.
+ Termination of Robinson's unification algorithm leveraging lean's dependent type system.
+ A partial soundness result for inference.

= Background and Definitions

== Simply Typed Lambda Calculus

#definition[
  The set $"CurryType"$ of _simple types_ is generated by the grammar
  $
    tau, sigma ::= phi_p | tau arrow.r sigma
  $
  where $p$ ranges over an alphabet of _type variables_ (characters) and $arrow.r$ is right-associative function-type formation.
]

#definition[
  The set $"Term"$ of _lambda terms_ is generated by the grammar
  $
    t, s ::= x | lambda x . t | t " " s
  $
  where $x$ ranges over a set of _term variables_ (characters).
]

#definition[
  A _typing context_ $Gamma$ is a finite list of pairs $(x, tau) in "Char" times "CurryType"$ together with a _label_ $ell in "Char"$ used as a counter for allocating fresh type variables. We write $Gamma(x)$ for the first type assigned to $x$ in $Gamma$, if any. The empty context is $Gamma_emptyset = ([], "A")$. Context extension is written $Gamma + (x : tau) = ((x, tau) :: Gamma."env", Gamma."label")$.
]

#definition[
  The set of _free type variables_ of a type $tau$, written $"fv"(tau)$, is
  $
    "fv"(phi_p) &= brace.l p brace.r \
    "fv"(tau arrow.r sigma) &= "fv"(tau) union "fv"(sigma)
  $
]

#definition[
  Typing assignment $Gamma tack.r t : tau$ are defined by the three standard rules:
  $
    frac(Gamma(x) = tau, Gamma tack.r x : tau) quad \
    frac(
      Gamma + (x : tau_1) tack.r m : tau_2,
      Gamma tack.r lambda x . m : tau_1 arrow.r tau_2
    ) quad \
    frac(
      Gamma tack.r m : tau_1 arrow.r tau_2 quad Gamma tack.r n : tau_1,
      Gamma tack.r m " " n : tau_2
    )
  $
]

== Type Substitutions

#definition[
  A _type substitution_ is a function $S : "CurryType" -> "CurryType"$ that distributes over arrow types: $S(tau arrow.r sigma) = S(tau) arrow.r S(sigma)$. The _pointwise application_ of $S$ to a context $Gamma$ is $S(Gamma) = brace.l (x, S(tau)) | (x, tau) in Gamma brace.r$.
]

#let rpl(a, s, t) = $#t [#a := #s]$
#definition[
  For a type variable $alpha$ and type $sigma$, the _replacement_ $rpl(alpha, sigma, tau)$ substitutes $sigma$ for every free occurrence of $alpha$ in $tau$:
  $
    rpl(alpha, sigma, phi_alpha) &= sigma \
    rpl(alpha, sigma, phi_beta) &= phi_beta quad (beta eq.not alpha) \
    rpl(alpha, sigma, tau arrow.r tau') &= rpl(alpha, sigma, tau) arrow.r rpl(alpha, sigma, tau')
  $
]

= Implementation

== The `check` Function <sec-check>

The _type-checker_ `check` verifies whether a term follows type assignment rules. It requires the context to already contain all free variables of the term with their types. Its role in this formalisation is as the _specification_ against which `pp'` is proved sound.

#definition[
  $
    "check"(Gamma, x) = Gamma(x)
  $
  $
    "check"(Gamma, lambda x . m) = \
    cases(
      "none"\, "if" "check"(Gamma, m) = "none",
      "none"\, "if" "check"(Gamma, m)."isSome"\, Gamma(x) = "none",
      "some"(tau' arrow.r tau)\, "if" "check"(Gamma, m)."isSome"\, Gamma(x)."isSome",
    )
  $
  $
    "check"(Gamma, m space n) = \
    cases(
      "some"(tau_2)\, "if",
      quad quad "check"(Gamma,m) >>= "check"(Gamma,n) = "some"(tau_2),
      "none"\, "otherwise"
    )
  $
]

#figure(
  fletcher.diagram(
    node-stroke: 0.5pt,
    node-shape: rect,
    spacing: (2.5em, 1.5em),
    node((0, 0), $"check"(Gamma, t)$, shape: "rect"),
    edge((0, 0), (-1, 1), "->", label: $t = x$),
    edge((0, 0), (0, 1), "->", label: $t = lambda x.m$),
    edge((0, 0), (1, 1), "->", label: $t = m " " n$),
    node((-1, 1), [$Gamma(x)$], shape: "rect"),
    node((0, 1), [$"check"(Gamma,m)$], shape: "rect"),
    node((1, 1), [$"check"(Gamma,m)$\ $"check"(Gamma,n)$], shape: "rect"),
    edge((-1, 1), (-1, 2), "->"),
    node((-1, 2), [$"some"(tau)$ or $"none"$], shape: "rect"),
    edge((0, 1), (0, 2), "->", label: $"some"(tau)$),
    node((0, 2), [$Gamma(x)?$], shape: "rect"),
    edge((0, 2), (0, 3), "->", label: $"some"(tau')$),
    node((0, 3), [$"some"(tau' arrow.r tau)$], shape: "rect"),
    edge(
      (1, 1),
      (1, 2),
      "->",
      label: $\_ >>= \_ = "some" tau_2$,
    ),
    node((1, 2), [$"some"(tau_2)$], shape: "rect"),
  ),
  caption: [Control flow of `check`.],
) <fig-check>

== `Subst` <sec-subst>

A value $S : "Subst"(tau_1, tau_2)$ packages a substitution function $"apply"$ together with three propositions.

$
  P_1 &: forall tau. "fv"(f(tau)) subset.eq "fv"(tau_1) union "fv"(
    tau_2
  ) union "fv"(tau) \
  P_2 &: forall tau. lr(|"fv"(f(tau))|) = lr(|"fv"(tau_1) union "fv"(tau_2) union "fv"(tau)|) arrow.r.double f = "id" \
  P_3 &: forall a, b. f(a arrow.r b) = f(a) arrow.r f(b)
$

The four constructors of `Subst` and how they discharge the three invariants are
summarised in @tbl-subst.

#figure(
  table(
    columns: (auto, auto, auto, auto),
    align: (left, center, center, center),
    table.header(
      [*Constructor*],
      [$P_1$],
      [$P_2$],
      [$P_3$],
    ),

    [`id`], [Trivial], [Trivial], [Trivial],
    [`replace` $(alpha, sigma)$], [Trivial], [Lemma 4.1.6], [Trivial],
    [`replacer` $(alpha, sigma)$],
    [Lemma 4.1.3],
    [Ex falso via Lemma 4.1.6],
    [Trivial],

    [`comp`$(S_1, S_2)$], [`calc` and ind. hyp.], [4.2], [ind. hyp.],
  ),
  caption: [`Subst` constructors and their invariant proofs.],
) <tbl-subst>

The `replace` and `replacer` constructors discharge $P_2$ by contradiction.
The key auxiliary lemma (`ReplaceAddsNewVars`) shows that the cardinality
equality in $P_2$ can _never_ hold for a replacement substitution, so the implication is
vacuously true. The `comp` constructor uses a cardinality squeeze: it shows that the
cardinality of the image of $S_2 compose S_1$ equals that of the combined variable set,
then peels off $S_2 = "id"$ and subsequently $S_1 = "id"$ by two successive applications
of $P_2$.

== The `unify` Algorithm <sec-unify>

#definition[
  $"unify" : "CurryType" times "CurryType" -> "Option"("Subst"(tau_1, tau_2))$ is defined
  by the following case analysis. Let $"occ"(p, tau)$ denote the occurs-check predicate
  (true iff $p in "fv"(tau)$).

  $
    &"unify"(phi_p, phi_p) = "some"("id") \
    &"unify"(phi_p, phi_q)\, p eq.not q = "some"("replace"(p, phi_q)) \
    &"unify"(phi_p, tau)\, not "occ"(p,tau) = "some"("replace"(p, tau)) \
    &"unify"(phi_p, tau)\, "occ"(p,tau) = "none" \
    &"unify"(tau, phi_p)\, not "occ"(p,tau) = "some"("replacer"(p, tau)) \
    &"unify"(tau, phi_p)\, "occ"(p,tau) = "none"
  $

  For the arrow case, let $"u"_1 = "unify"(tau, sigma)$ and $"u"_2 = "unify"(S_1(tau'), S_1(sigma'))$:
  $
    "unify"(tau arrow.r tau', sigma arrow.r sigma') = \
    cases(
      "none" quad "if" "u"_1 = "none",
      "none" quad "if" "u"_1 = "some"(S_1)\, "u"_2 = "none",
      "some"("comp"(S_1, S_2)) quad "if" "u"_1 = "some"(S_1)\, "u"_2 = "some"(S_2),
    )
  $
]

=== Termination of `unify` <sec-term>

Termination of `unify` is non-trivial because the arrow case makes _two_ recursive calls
and the second call is on the $S_1$-image of the tails, not on the original tails.

#theorem("Termination of `unify`")[
  The function `unify` terminates under the lexicographic measure
  $
    mu(tau_1, tau_2) = (
      lr(|"fv"(tau_1) union "fv"(tau_2)|); "sz"(tau_1) + "sz"(tau_2)
    )
  $
]

#proof[
  We show that each recursive call strictly decreases $mu$.

  *First call* $"unify"(tau, sigma)$ from the case $"unify"(tau arrow.r tau', sigma arrow.r sigma')$:
  $
    "fv"(tau) union "fv"(sigma) subset.eq "fv"(tau arrow.r tau') union "fv"(
      sigma arrow.r sigma'
    )
  $
  by definition of $"fv"$, so the cardinality does not increase.
  Since $"sz"(tau) + "sz"(sigma) < "sz"(tau arrow.r tau') + "sz"(sigma arrow.r sigma')$,
  the "pair" $(|"fv"|, "sz")$ decreases lexicographically (either the cardinality drops, or
  it stays equal while the size drops).

  *Second call* $"unify"(S_1(tau'), S_1(sigma'))$:
  The cardinality may or may not decrease. If it decreases strictly, we are done.
  Otherwise the cardinality is preserved, which by invariant $P_2$ of $S_1$ forces
  $S_1 = "id"$.
  When $S_1 = "id"$, simplification gives that the size decreased.
]

== Context Unification `unifyCtx` <sec-unifyctx>

#definition[
  Let $"dom"(Gamma)$ denote the set of variables in the domain of $Gamma$.
  Define the set of _common variable pairs_
  $
    C = brace.l (x, Gamma_1(x), Gamma_2(x)) | x in "dom"(Gamma_1) inter "dom"(
      Gamma_2
    ) brace.r
  $
  The algorithm $"unifyCtx"(Gamma_1, Gamma_2)$ computes the composed substitution
  $
    "apply" := \u{229A}_((\_, tau_1, tau_2) in C) "unify"(tau_1, tau_2)
  $
]

#remark([`ExSubst` and type erasure])[
  Each $S_x = "unify"(tau_x, sigma_x)$ has type $"Subst"(tau_x, sigma_x)$, where the index types differ for each $x$. To store them in a homogeneous list, the formalisation introduces a wrapper that erased the dependent types. The function `ExSubst.cast` extracts the underlying `apply` function. This erases the type indices while retaining the distributivity property needed to prove $P_3$ of the composed `CtxSubst`.
]

== Principal-Pair Algorithm `pp'` <sec-pp>

#definition[
  The helper $"pp'" : "TypeCtx" times "Term" -> "Option"("PrincipalPair")$ is defined by cases on the term.

  *Variable case.* Let $(alpha, Gamma') = "next"(Gamma)$:
  $
    "pp'"(Gamma, x) = \
    cases(
      "some"(Gamma, tau) quad "if" Gamma(x) = "some"(tau),
      "some"(Gamma' + (x : alpha), alpha) quad "if" Gamma(x) = "none",
    )
  $

  *Abstraction case.* Let $(alpha, Gamma'') = "next"(Gamma')$:
  $
    "pp'"(Gamma, lambda x . m) = \
    cases(
      "none" quad "if" "pp'"(Gamma, m) = "none",
      "some"(Gamma', tau' arrow.r tau),
      quad quad "if" "pp'"(Gamma,m) = "some"(Gamma', tau) "and" Gamma'(x) = "some"(tau'),
      "some"(Gamma'' + (x : alpha), alpha arrow.r tau),
      quad quad "if" "pp'"(Gamma,m) = "some"(Gamma',tau) "and" Gamma'(x) = "none",
    )
  $

  *Application case.*

  $(Gamma_1, pi_1) = "pp'"(Gamma, m)$,\
  $quad (Gamma_2, pi_2) = "pp'"(Gamma_1, n)$\
  $quad (alpha, Gamma_3) = "next"(Gamma_2)$,\
  $quad S_1 = "unify"(pi_1, pi_2 arrow.r alpha)$\
  $quad S_2 = "unifyCtx"(S_1(Gamma_1), S_1(Gamma_3))$, then\
  $
    "pp'"(Gamma, m space n) = "some"(S_2(S_1(Gamma_3)), S_2(S_1(alpha)))
  $
]

The top-level function $"pp"(t) := "pp'"(Gamma_emptyset, t)$.

= Structural Lemmas

This section catalogues all proven lemmas and theorems. Many are straightforward; we
highlight the non-trivial ones.

== Free Variable Lemmas

#lemma([`SizeGtZ`])[
  Every type has strictly positive size: $forall tau in "CurryType", "sz"(tau) > 0$.
]

#lemma([`VarsArrow`])[
  $forall tau, tau' in "CurryType", "fv"(tau) subset.eq "fv"(tau arrow.r tau')$.
]

#lemma([`ReplaceVarScope`])[
  If $not "occ"(alpha, sigma)$ then $forall tau, "fv"(rpl(alpha, sigma, tau)) subset.eq brace.l alpha brace.r union "fv"(sigma) union "fv"(tau)$.
]

#lemma([`OccursInIffInVars`])[
  $forall c in "Char", forall tau in "CurryType", c in "fv"(tau) => "occ"(c, tau) = "true"$.
]

#lemma([`ReplaceElim`])[
  If $not "occ"(alpha, sigma)$ then $forall tau, alpha in.not "fv"(rpl(alpha, sigma, tau))$.
]

#lemma([`ReplaceAddsNewVars`])[
  If $not "occ"(alpha, sigma)$ then $forall tau$: $lr(|"fv"(rpl(alpha, sigma, tau))|) eq.not lr(|"fv"(phi_alpha) union "fv"(sigma) union "fv"(tau)|)$
]

#proof[
  Suppose for contradiction that
  $lr(|"fv"(rpl(alpha, sigma, tau))|) = lr(|"fv"(phi_alpha) union "fv"(sigma) union "fv"(tau)|)$.

  Let $L = "fv"(rpl(alpha, sigma, tau))$ and $R = brace.l alpha brace.r union "fv"(sigma) union "fv"(tau)$.

  _Step 1 (strict subset)._ By Lemma 4.3, $L subset.eq R$. By Lemma 4.5, $alpha in.not L$. Since $alpha in R$ (it belongs to $brace.l alpha brace.r subset.eq R$), we have $L subset.neq R$.

  _Step 2 (contradiction)._ The Mathlib lemma `Finset.eq_of_subset_of_card_le` @mathlib states: if $A subset.eq B$ and $lr(|B|) lt.eq lr(|A|)$ then $A = B$. Since $lr(|L|) = lr(|R|)$, we have $lr(|R|) lt.eq lr(|L|)$, so $L = R$. But $alpha in R$ and $alpha in.not L$: contradiction.
]

== Structural Properties of `check`

#lemma([`CheckInvUnderLabel`])[
  $"check"$ depends only on the `env` field of a context, not on the `label`:
  $
    forall t, Gamma."env" = Gamma'."env" => "check"(Gamma, t) = "check"(
      Gamma', t
    ).
  $
]

#lemma([`CheckInvUnderNextSubst`])[
  Applying a substitution commutes with advancing the fresh-variable counter:
  $
    "check"("applySubst"(f, Gamma), m) =\
    "check"("applySubst"(f, "next"(Gamma).2), m)
  $
]

#lemma([`EnvInvUnderSubst`])[
  $"applySubst"$ preserves environment equality:
  $
    Gamma."env" = Gamma'."env" => \
    ("applySubst"(f, Gamma))."env" = ("applySubst"(f, Gamma'))."env".
  $
]

#lemma([`LookupMap`])[
  List lookup commutes with mapping:
  $
    "lookup"(x, "xys") = "some"(y) =>\
    "lookup"(x, "map"("xys"."map"(S)) = "some"(S(y)).
  $
]

#lemma([`CheckInvUnderAdd`])[
  If $Gamma'(x) = "none"$ and $"ctx" = Gamma' + (x : alpha)$ and $m eq.not "var" x$ and
  $"check"(Gamma', m) = "some"(pi)$, then $"check"("ctx", m) = "some"(pi)$.
]

In other words, adding a binding for an unused variable to the context does not affect checking any term that does not consist solely of that variable.

#proof[
  By structural induction on $m$.

  *Case $m = "var" c$, $c eq.not x$*: The new context has env $(x, alpha) :: Gamma'."env"$. Lookup proceeds: since $c eq.not x$ and the `BEq` instance is `LawfulBEq`, the head is skipped, and `lookup c` falls through to $Gamma'."env"$, returning the same value.

  *Case $m = lambda y . m'$*: We have $"check"(Gamma', m') = "some"(tau)$ for some $tau$ and
  $Gamma'(y) = "some"(tau')$. The induction hypothesis applies to $m'$ if $m' eq.not "var" x$. But if $m' = "var" x$ then $"check"(Gamma', "var" x) = Gamma'(x) = "none"$, contradicting the hypothesis that $"check"(Gamma', m') = "some"(tau)$. Thus $m' eq.not "var" x$ and IH applies, giving $"check"("ctx", m') = "some"(tau)$. For the lookup of $y$: since $x eq.not y$ (if $x = y$ then $Gamma'(x) = "none"$ but $Gamma'(y) = "some"(tau')$ — a contradiction since the lookup is deterministic), lookup of $y$ in the extended context returns $Gamma'(y) = "some"(tau')$.

  *Case $m = m_1 " " m_2$*: Apply IH to both $m_1$ and $m_2$ (they inherit $m eq.not "var" x$ by a similar `check`-produces-`none`-if-only-var-is-$x$ argument).
]

#lemma([`SubstComp`])[
  $
    "applySubst"(f, "applySubst"(g, Gamma))\
    = "applySubst"(f compose g, Gamma)
  $
]

#theorem([`CheckSubst`])[
  If $"check"(Gamma, t) = "some"(tau)$ and $S$ distributes over arrows, then
  $"check"("applySubst"(S, Gamma), t) = "some"(S(tau))$.
]

#proof[
  By structural induction on $t$.

  *Case $t = "var" c$*: Apply Lemma 4.10 (`LookupMap`) to the hypothesis $Gamma(c) = tau$.

  *Case $t = lambda x . m$*: Let $"check"(Gamma, m) = "some"(tau_m)$ and $Gamma(x) = "some"(tau')$. The IH gives $"check"("applySubst"(S, Gamma), m) = "some"(S(tau_m))$. By Lemma 4.10, $"applySubst"(S, Gamma)(x) = "some"(S(tau'))$. Composing: $"check"(dots) = "some"(S(tau') arrow.r S(tau_m)) = "some"(S(tau' arrow.r tau_m))$ using $P_3$ of $S$.

  *Case $t = m " " n$*: Let $"check"(Gamma, m) = "some"(a arrow.r b)$ and
  $"check"(Gamma, n) = "some"(a)$ with $a == a$ (i.e. $a = a$ via `LawfulBEq`). The IH gives $"check"(S(Gamma), m) = "some"(S(a) arrow.r S(b))$ (using $P_3$ of $S$ for the arrow) and $"check"(S(Gamma), n) = "some"(S(a))$. Since `LawfulBEq` guarantees $S(a) == S(a)$, the branch returns $"some"(S(b)) = "some"(S(tau))$. (The argument uses `beq_iff_eq.mp` to convert the `BEq` condition to propositional equality.)
]

#theorem([`SubstMap`])[
  If $S_1(tau) = S_1(a) arrow.r S_1(b)$ then
  $(S_2 compose S_1)(tau) = (S_2 compose S_1)(a) arrow.r (S_2 compose S_1)(b)$.
]

= Soundness of Unification

#theorem([`UnifySound`])[
  If $"unify"(tau_1, tau_2) = "some"(S)$ then $S(tau_1) = S(tau_2)$.
]

This is the _soundness_ of unification: every output of `unify` is a genuine unifier.

#proof[
  The proof proceeds by Lean 4's functional induction tactic `unify.induct` @lean4, which
  generates one goal per branch of `unify`'s definition.

  *Case $tau_1 = tau_2 = phi_p$*:

  $S = "id"$, so $S(phi_p) = phi_p = S(phi_p)$.

  *Case $tau_1 = phi_p$, $tau_2 = phi_q$, $p eq.not q$*:

  $S = "replace"(p, phi_q)$. By definition of `replaceVar`, $S(phi_p) = phi_q$ and $S(phi_q) = phi_q$, so the equation holds.

  *Case $tau_1 = phi_p$, $tau_2 = tau$, $not "occ"(p, tau)$*:

  $S = "replace"(p, tau)$. We need $S(phi_p) = S(tau)$. $S(phi_p) = tau$ by definition of `replaceVar`. For $S(tau) = tau$: since $not "occ"(p, tau)$, the variable $p$ does not appear in $tau$, so `replaceVar` acts as the identity on $tau$ (proved by the auxiliary $forall sigma, tau, not "occ"(p, tau) => rpl(p, sigma, tau) = tau$ by induction on $tau$). Hence both sides equal $tau$.

  *Case $tau_1 = phi_p$, $tau_2 = tau$, $"occ"(p, tau)$*:

  `unify` returns `none`; there is no $S$ to consider.

  *Case $tau_1 = a arrow.r b$, $tau_2 = c arrow.r d$, $"unify"(a,c) = "none"$* or

  $"unify"(S_1(b), S_1(d)) = "none"$: similarly `none`; no $S$.

  *Case $tau_1 = a arrow.r b$, $tau_2 = c arrow.r d$, $S = "comp"(S_1, S_2)$*:

  By induction hypothesis, $S_1(a) = S_1(c)$ and $S_2(S_1(b)) = S_2(S_1(d))$.
  $
    &S(a arrow.r b)\
    &= S_2(S_1(a arrow.r b))\
    &= S_2(S_1(a) arrow.r S_1(b))\
    &= S_2(S_1(a)) arrow.r S_2(S_1(b)) \
    \
    &S(c arrow.r d)\
    &= S_2(S_1(c arrow.r d))\
    &= S_2(S_1(c) arrow.r S_1(d))\
    &= S_2(S_1(c)) arrow.r S_2(S_1(d))
  $
  Since $S_1(a) = S_1(c)$ and $S_2(S_1(b)) = S_2(S_1(d))$, the two sides are equal.

  *Case $tau_1 = tau$, $tau_2 = phi_p$, $not "occ"(p, tau)$*:
  $S = "replacer"(p, tau)$, which has the same `apply` as `replace(p, τ)`.
  The same argument as the symmetric case above applies (using the same `replace_no_occ` auxiliary).
  $S(tau) = tau$ since $not "occ"(p, tau)$, and $S(phi_p) = tau$ by definition.
]

= Soundness of Inference

#lemma([`InferenceSound'`])[
  If $"pp'"(Gamma, t) = "some"(p)$ then $"check"(p."ctx", t) = "some"(p."ty")$.
]

#proof[
  By structural induction on $t$.

  *Case $t = "var" c$, $Gamma(c) = "some"(tau)$*: `pp'` returns $(Gamma, tau)$.
  `check(Γ, var c) = Γ(c) = some τ`.

  *Case $t = "var" c$, $Gamma(c) = "none"$*: Let $(alpha, Gamma') = "next"(Gamma)$.
  `pp'` returns $(Gamma' + (c : alpha), alpha)$.
  `check(Γ' + (c:α), var c) = lookup c ((c,α)::env) = some α`.

  *Case $t = lambda x . m$, $Gamma'(x) = "some"(tau')$*:
  IH gives $"check"(Gamma', m) = "some"(tau)$.
  `check(Γ', λx.m)` returns $"some"(tau' arrow.r tau)$ since $Gamma'(x) = "some"(tau')$.

  *Case $t = lambda x . m$, $Gamma'(x) = "none"$*:
  `pp'` allocates $alpha = "next"(Gamma')$ and returns $(Gamma'' + (x:alpha), alpha arrow.r tau)$.
  The IH gives $"check"(Gamma', m) = "some"(tau)$.
  Lemma 4.11 (`CheckInvUnderAdd`) lifts this to $"check"(Gamma'' + (x:alpha), m) = "some"(tau)$
  (since $m eq.not "var" x$: if $m = "var" x$ then $"check"(Gamma', "var" x) = Gamma'(x) = "none"$,
  contradicting the IH).
  Lookup of $x$ in the extended context succeeds with $alpha$.

  *Case $t = m " " n$ (application)*:
  The proof is mostly complete. It establishes the soundness of the variable and abstraction
  cases by applying `CheckSubst` (Theorem 4.13) and the commutativity lemmas.
  The final step — assembling the composed substitution in the case where
  $"check"("ctx", m) = "some"(tau_1 arrow.r tau_2)$ with $tau_1 = tau_n$ — requires
  connecting $"UnifySound"$ (Theorem 5.1) to the output type of `pp'`.
  This final connection is left as an open item (`sorry` in the current development).
]

#theorem([`InferenceSound`])[
  If $"pp"(t) = "some"(p)$ then $"check"(p."ctx", t) = "some"(p."ty")$.
]

#proof[
  $"pp"(t) = "pp'"(Gamma_emptyset, t)$. Apply Lemma 6.1 directly.
]

#corollary[
  If $"pp"(t) = "some"(p)$ then $p."ctx" tack.r t : p."ty"$ in the sense of Definition 2.5.
]

= Conclusion and Future Work

We have described an incomplete Lean 4 formalisation of principal type inference for the STLC.

The primary open item is the application case of `InferenceSound'`. The difficulty is
assembling the composed substitution $S_2 compose S_1$ from the outputs of `unify` and
`unifyCtx`, and showing that the final context and type satisfy `check`. This requires
a compatibility lemma relating `unifyCtx`'s action on $S_1(Gamma_1)$ and $S_1(Gamma_3)$
to the checking of $m$ and $n$ respectively.

Future directions include:

+ Complete the sorried proofs.
+ Extend the proof for more complex systems, such as Lambda calculus with names and recursion (LCNR) or Milner's ML.

= AI Assistance Acknowledgement

The formalisation presented in this paper was developed with the assistance of an AI language model, specifically *DeepSeek* @deepseek. The AI was employed in two complementary roles:

- *As an enhanced `grind` tactic* – Many set-theoretic lemmas (e.g., subset inclusions, cardinality reasoning, and elementary facts about finite sets) were initially sketched by the AI. These proofs, while mathematically straightforward, can be tedious to write out in full detail. The AI provided high‑level proof sketches that could be refined into complete Lean proofs, effectively acting as an “intelligent `grind`”. This accelerated the development of lemmas such as `ReplaceVarScope`, `ReplaceElim`, and the various auxiliary facts used in the termination argument for `unify`.

- *As a proof‑state summariser* – During the construction of complex inductive proofs (notably `CheckInvUnderAdd` and the application case of `InferenceSound'`), the AI was used to summarise the current hypotheses and goals. By prompting the model with the current proof context, it helped keep track of numerous side conditions and filter out the irrelevant ones.

All AI‑generated proof sketches were carefully reviewed, corrected, and simplified.
